"""
github/branch_manager.py

Branch naming and management utilities for the auto-fix workflow.

Architecture role:
  - Used by the Auto-Fix Agent to generate deterministic fix branch names
  - Ensures no naming collisions between concurrent fix workflows
  - Called by github_client.py to create and push fix branches
"""

from __future__ import annotations

import re
from datetime import datetime, timezone


def generate_fix_branch_name(pr_number: int, finding_id: str) -> str:
    """
    Generate a deterministic fix branch name.

    Format: ai-fix/pr-{pr_number}/{finding_id_short}
    Example: ai-fix/pr-42/abc12345

    Uses finding ID prefix for uniqueness when one PR has multiple fixes.
    """
    short_id = finding_id[:8]
    return f"ai-fix/pr-{pr_number}/{short_id}"


def generate_batch_fix_branch_name(pr_number: int) -> str:
    """
    Generate a branch name for a batch of fixes from one PR.

    Format: ai-fix/pr-{pr_number}/batch-{timestamp}
    Example: ai-fix/pr-42/batch-20240115-143022
    """
    ts = datetime.now(tz=timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"ai-fix/pr-{pr_number}/batch-{ts}"


def sanitize_branch_name(name: str) -> str:
    """
    Sanitize an arbitrary string to be a valid git branch name.

    - Replace spaces and invalid chars with hyphens
    - Strip leading/trailing hyphens
    - Lowercase
    - Truncate to 100 chars
    """
    sanitized = re.sub(r"[^a-zA-Z0-9._/-]", "-", name)
    sanitized = re.sub(r"-+", "-", sanitized)
    sanitized = sanitized.strip("-").lower()
    return sanitized[:100]


def fix_commit_message(file_path: str, issue_summary: str) -> str:
    """
    Generate a conventional commit message for an AI-generated fix.
    """
    short_issue = issue_summary[:72] if len(issue_summary) > 72 else issue_summary
    return f"fix: {short_issue}\n\nAI-generated fix for {file_path}\nGenerated by github-ai-review-agent"